SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

INSERT INTO `provincias` (`id`, `provincia`, `provincia_url`) VALUES
(1, 'Araba/Álava', 'araba-alava'),
(2, 'Albacete', 'albacete'),
(3, 'Alicante', 'alicante'),
(4, 'Almería', 'almeria'),
(5, 'Asturias', 'asturias'),
(6, 'Ávila', 'avila'),
(7, 'Badajoz', 'badajoz'),
(8, 'Barcelona', 'barcelona'),
(9, 'Burgos', 'burgos'),
(10, 'Cáceres', 'caceres'),
(11, 'Cádiz', 'cadiz'),
(12, 'Cantabria', 'cantabria'),
(13, 'Castellón', 'castellon'),
(14, 'Ciudad Real', 'ciudad-real'),
(15, 'Córdoba', 'cordoba'),
(16, 'A Coruña', 'a-coruna'),
(17, 'Cuenca', 'cuenca'),
(18, 'Girona', 'girona'),
(19, 'Granada', 'granada'),
(20, 'Guadalajara', 'guadalajara'),
(21, 'Gipuzkoa', 'gipuzkoa'),
(22, 'Huelva', 'huelva'),
(23, 'Huesca', 'huesca'),
(24, 'Illes Balears', 'illes-balears'),
(25, 'Jaén', 'jaen'),
(26, 'León', 'leon'),
(27, 'Lleida', 'lleida'),
(28, 'Lugo', 'lugo'),
(29, 'Madrid', 'madrid'),
(30, 'Málaga', 'malaga'),
(31, 'Murcia', 'murcia'),
(32, 'Navarra', 'navarra'),
(33, 'Ourense', 'ourense'),
(34, 'Palencia', 'palencia'),
(35, 'Las Palmas', 'las-palmas'),
(36, 'Pontevedra', 'pontevedra'),
(37, 'La Rioja', 'la-rioja'),
(38, 'Salamanca', 'salamanca'),
(39, 'Segovia', 'segovia'),
(40, 'Sevilla', 'sevilla'),
(41, 'Soria', 'soria'),
(42, 'Tarragona', 'tarragona'),
(43, 'Santa Cruz de Tenerife', 'santa-cruz-de-tenerife'),
(44, 'Teruel', 'teruel'),
(45, 'Toledo', 'toledo'),
(46, 'Valencia', 'valencia'),
(47, 'Valladolid', 'valladolid'),
(48, 'Vizcaya', 'vizcaya'),
(49, 'Zamora', 'zamora'),
(50, 'Zaragoza', 'zaragoza');
