-- Municipios Barcelona

INSERT INTO `municipios` (`id`, `id_pro`, `municipio`, `municipio_url`) VALUES
(1, 8, 'Abrera', 'abrera'),
(2, 8, 'Aguilar de Segarra', 'aguilar-de-segarra'),
(3, 8, 'Aiguafreda', 'aiguafreda'),
(4, 8, 'Alella', 'alella'),
(5, 8, 'Alpens', 'alpens'),
(6, 8, 'Arenys de Mar', 'arenys-de-mar'),
(7, 8, 'Arenys de Munt', 'arenys-de-munt'),
(8, 8, 'Argençola', 'argençola'),
(9, 8, 'Argentona', 'argentona'),
(10, 8, 'Artés', 'artes'),
(11, 8, 'Avià', 'avia'),
(12, 8, 'Avinyó', 'avinyo'),
(13, 8, 'Avinyonet del Penedès', 'avinyonet-del-penedes'),
(14, 8, 'Badalona', 'badalona'),
(15, 8, 'Badia del Vallès', 'badia-del-valles'),
(16, 8, 'Bagà', 'baga'),
(17, 8, 'Balenyà', 'balenya'),
(18, 8, 'Balsareny', 'balsareny'),
(19, 8, 'Barberà del Vallès', 'barbera-del-valles'),
(20, 8, 'Barcelona', 'barcelona'),
(21, 8, 'Begues', 'begues'),
(22, 8, 'Bellprat', 'bellprat'),
(23, 8, 'Berga', 'berga'),
(24, 8, 'Bigues i Riells', 'bigues-i-riells'),
(25, 8, 'Borredà', 'borreda'),
(26, 8, 'Cabrera d''Anoia', 'cabrera-d-anoia'),
(27, 8, 'Cabrera de Mar', 'cabrera-de-mar'),
(28, 8, 'Cabrils', 'cabrils'),
(29, 8, 'Calaf', 'calaf'),
(30, 8, 'Calders', 'calders'),
(31, 8, 'Caldes d''Estrac', 'caldes-d-estrac'),
(32, 8, 'Caldes de Montbui', 'caldes-de-montbui'),
(33, 8, 'Calella', 'calella'),
(34, 8, 'Calldetenes', 'calldetenes'),
(35, 8, 'Callús', 'callus'),
(36, 8, 'Calonge de Segarra', 'calonge-de-segarra'),
(37, 8, 'Campins', 'campins'),
(38, 8, 'Canet de Mar', 'canet-de-mar'),
(39, 8, 'Canovelles', 'canovelles'),
(40, 8, 'Cànoves i Samalús', 'canoves-i-samalus'),
(41, 8, 'Canyelles', 'canyelles'),
(42, 8, 'Capellades', 'capellades'),
(43, 8, 'Capolat', 'capolat'),
(44, 8, 'Cardedeu', 'cardedeu'),
(45, 8, 'Cardona', 'cardona'),
(46, 8, 'Carme', 'carme'),
(47, 8, 'Casserres', 'casserres'),
(48, 8, 'Castell de l''Areny', 'castell-de-l-areny'),
(49, 8, 'Castellar de n''Hug', 'castellar-de-n-hug'),
(50, 8, 'Castellar del Riu', 'castellar-del-riu'),
(51, 8, 'Castellar del Vallès', 'castellar-del-valles'),
(52, 8, 'Castellbell i el Vilar', 'castellbell-i-el-vilar'),
(53, 8, 'Castellbisbal', 'castellbisbal'),
(54, 8, 'Castellcir', 'castellcir'),
(55, 8, 'Castelldefels', 'castelldefels'),
(56, 8, 'Castellet i la Gornal', 'castellet-i-la-gornal'),
(57, 8, 'Castellfollit de Riubregós', 'castellfollit-de-riubregos'),
(58, 8, 'Castellfullit del Boix', 'castellfullit-del-boix'),
(59, 8, 'Castellgalí', 'castellgali'),
(60, 8, 'Castellnou de Bages', 'castellnou-de-bages'),
(61, 8, 'Castellolí', 'castelloli'),
(62, 8, 'Castellterçol', 'castellterçol'),
(63, 8, 'Castellví de la Marca', 'castellvi-de-la-marca'),
(64, 8, 'Castellví de Rosanes', 'castellvi-de-rosanes'),
(65, 8, 'Centelles', 'centelles'),
(66, 8, 'Cercs', 'cercs'),
(67, 8, 'Cerdanyola del Vallès', 'cerdanyola-del-valles'),
(68, 8, 'Cervelló', 'cervello'),
(69, 8, 'Collbató', 'collbato'),
(70, 8, 'Collsuspina', 'collsuspina'),
(71, 8, 'Copons', 'copons'),
(72, 8, 'Corbera de Llobregat', 'corbera-de-llobregat'),
(73, 8, 'Cornellà de Llobregat', 'cornella-de-llobregat'),
(74, 8, 'Cubelles', 'cubelles'),
(75, 8, 'Dosrius', 'dosrius'),
(76, 8, 'El Bruc', 'el-bruc'),
(77, 8, 'El Brull', 'el-brull'),
(78, 8, 'El Masnou', 'el-masnou'),
(79, 8, 'El Pla del Penedès', 'el-pla-del-penedes'),
(80, 8, 'El Prat de Llobregat', 'el-prat-de-llobregat'),
(81, 8, 'Els Hostalets de Pierola', 'els-hostalets-de-pierola'),
(82, 8, 'Els Prats de Rei', 'els-prats-de-rei'),
(83, 8, 'Esparreguera', 'esparreguera'),
(84, 8, 'Esplugues de Llobregat', 'esplugues-de-llobregat'),
(85, 8, 'Figaró-Montmany', 'figaro-montmany'),
(86, 8, 'Fígols', 'figols'),
(87, 8, 'Fogars de la Selva', 'fogars-de-la-selva'),
(88, 8, 'Fogars de Montclús', 'fogars-de-montclus'),
(89, 8, 'Folgueroles', 'folgueroles'),
(90, 8, 'Fonollosa', 'fonollosa'),
(91, 8, 'Fontrubí', 'fontrubi'),
(92, 8, 'Gaià', 'gaia'),
(93, 8, 'Gallifa', 'gallifa'),
(94, 8, 'Gavà', 'gava'),
(95, 8, 'Gelida', 'gelida'),
(96, 8, 'Gironella', 'gironella'),
(97, 8, 'Gisclareny', 'gisclareny'),
(98, 8, 'Granera', 'granera'),
(99, 8, 'Granollers', 'granollers'),
(100, 8, 'Gualba', 'gualba'),
(101, 8, 'Guardiola de Berguedà', 'guardiola-de-bergueda'),
(102, 8, 'Gurb', 'gurb'),
(103, 8, 'Igualada', 'igualada'),
(104, 8, 'Jorba', 'jorba'),
(105, 8, 'l''Ametlla del Vallès', 'l-ametlla-del-valles'),
(106, 8, 'L''Espunyola', 'l-espunyola'),
(107, 8, 'L''Estany', 'l-estany'),
(108, 8, 'L''Hospitalet de Llobregat', 'l-hospitalet-de-llobregat'),
(109, 8, 'La Garriga', 'la-garriga'),
(110, 8, 'La Granada', 'la-granada'),
(111, 8, 'La Llacuna', 'la-llacuna'),
(112, 8, 'La Llagosta', 'la-llagosta'),
(113, 8, 'La Nou de Berguedà', 'la-nou-de-bergueda'),
(114, 8, 'La Pobla de Claramunt', 'la-pobla-de-claramunt'),
(115, 8, 'La Quar', 'la-quar'),
(116, 8, 'La Roca del Vallès', 'la-roca-del-valles'),
(117, 8, 'Les Cabanyes', 'les-cabanyes'),
(118, 8, 'Les Franqueses del Vallès', 'les-franqueses-del-valles'),
(119, 8, 'Les Masies de Roda', 'les-masies-de-roda'),
(120, 8, 'Les Masíes de Voltregà', 'les-masies-de-voltrega'),
(121, 8, 'Lliçà d''Amunt', 'lliça-d-amunt'),
(122, 8, 'Lliçà de Vall', 'lliça-de-vall'),
(123, 8, 'Llinars del Vallès', 'llinars-del-valles'),
(124, 8, 'Lluçà', 'lluça'),
(125, 8, 'Malgrat de Mar', 'malgrat-de-mar'),
(126, 8, 'Malla', 'malla'),
(127, 8, 'Manlleu', 'manlleu'),
(128, 8, 'Manresa', 'manresa'),
(129, 8, 'Marganell', 'marganell'),
(130, 8, 'Martorell', 'martorell'),
(131, 8, 'Martorelles', 'martorelles'),
(132, 8, 'Masquefa', 'masquefa'),
(133, 8, 'Matadepera', 'matadepera'),
(134, 8, 'Mataró', 'mataro'),
(135, 8, 'Mediona', 'mediona'),
(136, 8, 'Moià', 'moia'),
(137, 8, 'Molins de Rei', 'molins-de-rei'),
(138, 8, 'Mollet del Vallès', 'mollet-del-valles'),
(139, 8, 'Monistrol de Calders', 'monistrol-de-calders'),
(140, 8, 'Monistrol de Montserrat', 'monistrol-de-montserrat'),
(141, 8, 'Montcada i Reixac', 'montcada-i-reixac'),
(142, 8, 'Montclar', 'montclar'),
(143, 8, 'Montesquiu', 'montesquiu'),
(144, 8, 'Montgat', 'montgat'),
(145, 8, 'Montmajor', 'montmajor'),
(146, 8, 'Montmaneu', 'montmaneu'),
(147, 8, 'Montmeló', 'montmelo'),
(148, 8, 'Montornès del Vallès', 'montornes-del-valles'),
(149, 8, 'Montseny', 'montseny'),
(150, 8, 'Muntanyola', 'muntanyola'),
(151, 8, 'Mura', 'mura'),
(152, 8, 'Navarcles', 'navarcles'),
(153, 8, 'Navas', 'navas'),
(154, 8, 'Òdena', 'odena'),
(155, 8, 'Olèrdola', 'olerdola'),
(156, 8, 'Olesa de Bonesvalls', 'olesa-de-bonesvalls'),
(157, 8, 'Olesa de Montserrat', 'olesa-de-montserrat'),
(158, 8, 'Olivella', 'olivella'),
(159, 8, 'Olost', 'olost'),
(160, 8, 'Olvan', 'olvan'),
(161, 8, 'Orís', 'oris'),
(162, 8, 'Oristà', 'orista'),
(163, 8, 'Orpí', 'orpi'),
(164, 8, 'Òrrius', 'orrius'),
(165, 8, 'Pacs del Penedès', 'pacs-del-penedes'),
(166, 8, 'Palafolls', 'palafolls'),
(167, 8, 'Palau-solità i Plegamans', 'palau-solita-i-plegamans'),
(168, 8, 'Pallejà', 'palleja'),
(169, 8, 'Palma de Cervelló', 'palma-de-cervello'),
(170, 8, 'Papiol', 'papiol'),
(171, 8, 'Parets del Vallès', 'parets-del-valles'),
(172, 8, 'Perafita', 'perafita'),
(173, 8, 'Piera', 'piera'),
(174, 8, 'Pineda de Mar', 'pineda-de-mar'),
(175, 8, 'Pobla de Lillet', 'pobla-de-lillet'),
(176, 8, 'Polinyà', 'polinya'),
(177, 8, 'Pont de Vilomara i Rocafort', 'pont-de-vilomara-i-rocafort'),
(178, 8, 'Pontons', 'pontons'),
(179, 8, 'Prats de Lluçanès', 'prats-de-lluçanes'),
(180, 8, 'Premià de Dalt', 'premia-de-dalt'),
(181, 8, 'Premià de Mar', 'premia-de-mar'),
(182, 8, 'Puig-reig', 'puig-reig'),
(183, 8, 'Puigdàlber', 'puigdalber'),
(184, 8, 'Pujalt', 'pujalt'),
(185, 8, 'Rajadell', 'rajadell'),
(186, 8, 'Rellinars', 'rellinars'),
(187, 8, 'Ripollet', 'ripollet'),
(188, 8, 'Roda de Ter', 'roda-de-ter'),
(189, 8, 'Rubí', 'rubi'),
(190, 8, 'Rubió', 'rubio'),
(191, 8, 'Rupit i Pruit', 'rupit-i-pruit'),
(192, 8, 'Sabadell', 'sabadell'),
(193, 8, 'Sagàs', 'sagas'),
(194, 8, 'Saldes', 'saldes'),
(195, 8, 'Sallent', 'sallent'),
(196, 8, 'Sant Adrià de Besòs', 'sant-adria-de-besos'),
(197, 8, 'Sant Agustí de Lluçanès', 'sant-agusti-de-lluçanes'),
(198, 8, 'Sant Andreu de la Barca', 'sant-andreu-de-la-barca'),
(199, 8, 'Sant Andreu de Llavaneres', 'sant-andreu-de-llavaneres'),
(200, 8, 'Sant Antoni de Vilamajor', 'sant-antoni-de-vilamajor'),
(201, 8, 'Sant Bartomeu del Grau', 'sant-bartomeu-del-grau'),
(202, 8, 'Sant Boi de Llobregat', 'sant-boi-de-llobregat'),
(203, 8, 'Sant Boi de Lluçanès', 'sant-boi-de-lluçanes'),
(204, 8, 'Sant Cebrià de Vallalta', 'sant-cebria-de-vallalta'),
(205, 8, 'Sant Celoni', 'sant-celoni'),
(206, 8, 'Sant Climent de Llobregat', 'sant-climent-de-llobregat'),
(207, 8, 'Sant Cugat del Vallès', 'sant-cugat-del-valles'),
(208, 8, 'Sant Cugat Sesgarrigues', 'sant-cugat-sesgarrigues'),
(209, 8, 'Sant Esteve de Palautordera', 'sant-esteve-de-palautordera'),
(210, 8, 'Sant Esteve Sesrovires', 'sant-esteve-sesrovires'),
(211, 8, 'Sant Feliu de Codines', 'sant-feliu-de-codines'),
(212, 8, 'Sant Feliu de Llobregat', 'sant-feliu-de-llobregat'),
(213, 8, 'Sant Feliu Sasserra', 'sant-feliu-sasserra'),
(214, 8, 'Sant Fost de Campsentelles', 'sant-fost-de-campsentelles'),
(215, 8, 'Sant Fruitós de Bages', 'sant-fruitos-de-bages'),
(216, 8, 'Sant Hipòlit de Voltregà', 'sant-hipolit-de-voltrega'),
(217, 8, 'Sant Iscle de Vallalta', 'sant-iscle-de-vallalta'),
(218, 8, 'Sant Jaume de Frontanyà', 'sant-jaume-de-frontanya'),
(219, 8, 'Sant Joan de Vilatorrada', 'sant-joan-de-vilatorrada'),
(220, 8, 'Sant Joan Despí', 'sant-joan-despi'),
(221, 8, 'Sant Julià de Cerdanyola', 'sant-julia-de-cerdanyola'),
(222, 8, 'Sant Julià de Vilatorta', 'sant-julia-de-vilatorta'),
(223, 8, 'Sant Just Desvern', 'sant-just-desvern'),
(224, 8, 'Sant Llorenç d''Hortons', 'sant-llorenç-d-hortons'),
(225, 8, 'Sant Llorenç Savall', 'sant-llorenç-savall'),
(226, 8, 'Sant Martí d''Albars', 'sant-marti-d-albars'),
(227, 8, 'Sant Martí de Centelles', 'sant-marti-de-centelles'),
(228, 8, 'Sant Martí de Tous', 'sant-marti-de-tous'),
(229, 8, 'Sant Martí Sarroca', 'sant-marti-sarroca'),
(230, 8, 'Sant Martí Sesgueioles', 'sant-marti-sesgueioles'),
(231, 8, 'Sant Mateu de Bages', 'sant-mateu-de-bages'),
(232, 8, 'Sant Pere de Ribes', 'sant-pere-de-ribes'),
(233, 8, 'Sant Pere de Riudebitlles', 'sant-pere-de-riudebitlles'),
(234, 8, 'Sant Pere de Torelló', 'sant-pere-de-torello'),
(235, 8, 'Sant Pere de Vilamajor', 'sant-pere-de-vilamajor'),
(236, 8, 'Sant Pere Sallavinera', 'sant-pere-sallavinera'),
(237, 8, 'Sant Pol de Mar', 'sant-pol-de-mar'),
(238, 8, 'Sant Quintí de Mediona', 'sant-quinti-de-mediona'),
(239, 8, 'Sant Quirze de Besora', 'sant-quirze-de-besora'),
(240, 8, 'Sant Quirze del Vallès', 'sant-quirze-del-valles'),
(241, 8, 'Sant Quirze Safaja', 'sant-quirze-safaja'),
(242, 8, 'Sant Sadurní d''Anoia', 'sant-sadurni-d-anoia'),
(243, 8, 'Sant Sadurní d''Osormort', 'sant-sadurni-d-osormort'),
(244, 8, 'Sant Salvador de Guardiola', 'sant-salvador-de-guardiola'),
(245, 8, 'Sant Vicenç de Castellet', 'sant-vicenç-de-castellet'),
(246, 8, 'Sant Vicenç de Montalt', 'sant-vicenç-de-montalt'),
(247, 8, 'Sant Vicenç de Torelló', 'sant-vicenç-de-torello'),
(248, 8, 'Sant Vicenç dels Horts', 'sant-vicenç-dels-horts'),
(249, 8, 'Santa Cecília de Voltregà', 'santa-cecilia-de-voltrega'),
(250, 8, 'Santa Coloma de Cervelló', 'santa-coloma-de-cervello'),
(251, 8, 'Santa Coloma de Gramenet', 'santa-coloma-de-gramenet'),
(252, 8, 'Santa Eugènia de Berga', 'santa-eugenia-de-berga'),
(253, 8, 'Santa Eulàlia de Riuprimer', 'santa-eulalia-de-riuprimer'),
(254, 8, 'Santa Eulàlia de Ronçana', 'santa-eulalia-de-ronçana'),
(255, 8, 'Santa Fe del Penedès', 'santa-fe-del-penedes'),
(256, 8, 'Santa Margarida de Montbui', 'santa-margarida-de-montbui'),
(257, 8, 'Santa Margarida i els Monjos', 'santa-margarida-i-els-monjos'),
(258, 8, 'Santa Maria d''Oló', 'santa-maria-d-olo'),
(259, 8, 'Santa Maria de Besora', 'santa-maria-de-besora'),
(260, 8, 'Santa Maria de Corcó', 'santa-maria-de-corco'),
(261, 8, 'Santa Maria de Martorelles', 'santa-maria-de-martorelles'),
(262, 8, 'Santa Maria de Merlès', 'santa-maria-de-merles'),
(263, 8, 'Santa Maria de Miralles', 'santa-maria-de-miralles'),
(264, 8, 'Santa Maria de Palautordera', 'santa-maria-de-palautordera'),
(265, 8, 'Santa Perpètua de Mogoda', 'santa-perpetua-de-mogoda'),
(266, 8, 'Santa Susanna', 'santa-susanna'),
(267, 8, 'Santpedor', 'santpedor'),
(268, 8, 'Sentmenat', 'sentmenat'),
(269, 8, 'Seva', 'seva'),
(270, 8, 'Sitges', 'sitges'),
(271, 8, 'Sobremunt', 'sobremunt'),
(272, 8, 'Sora', 'sora'),
(273, 8, 'Subirats', 'subirats'),
(274, 8, 'Súria', 'suria'),
(275, 8, 'Tagamanent', 'tagamanent'),
(276, 8, 'Talamanca', 'talamanca'),
(277, 8, 'Taradell', 'taradell'),
(278, 8, 'Tavèrnoles', 'tavernoles'),
(279, 8, 'Tavertet', 'tavertet'),
(280, 8, 'Teià', 'teia'),
(281, 8, 'Terrassa', 'terrassa'),
(282, 8, 'Tiana', 'tiana'),
(283, 8, 'Tona', 'tona'),
(284, 8, 'Tordera', 'tordera'),
(285, 8, 'Torelló', 'torello'),
(286, 8, 'Torre de Claramunt', 'torre-de-claramunt'),
(287, 8, 'Torrelavit', 'torrelavit'),
(288, 8, 'Torrelles de Foix', 'torrelles-de-foix'),
(289, 8, 'Torrelles de Llobregat', 'torrelles-de-llobregat'),
(290, 8, 'Ullastrell', 'ullastrell'),
(291, 8, 'Vacarisses', 'vacarisses'),
(292, 8, 'Vallbona d''Anoia', 'vallbona-d-anoia'),
(293, 8, 'Vallcebre', 'vallcebre'),
(294, 8, 'Vallgorguina', 'vallgorguina'),
(295, 8, 'Vallirana', 'vallirana'),
(296, 8, 'Vallromanes', 'vallromanes'),
(297, 8, 'Veciana', 'veciana'),
(298, 8, 'Vic', 'vic'),
(299, 8, 'Vilada', 'vilada'),
(300, 8, 'Viladecans', 'viladecans'),
(301, 8, 'Viladecavalls', 'viladecavalls'),
(302, 8, 'Vilafranca del Penedès', 'vilafranca-del-penedes'),
(303, 8, 'Vilalba Sasserra', 'vilalba-sasserra'),
(304, 8, 'Vilanova de Sau', 'vilanova-de-sau'),
(305, 8, 'Vilanova del Camí', 'vilanova-del-cami'),
(306, 8, 'Vilanova del Vallès', 'vilanova-del-valles'),
(307, 8, 'Vilanova i la Geltrú', 'vilanova-i-la-geltru'),
(308, 8, 'Vilassar de Dalt', 'vilassar-de-dalt'),
(309, 8, 'Vilassar de Mar', 'vilassar-de-mar'),
(310, 8, 'Vilobí del Penedès', 'vilobi-del-penedes'),
(311, 8, 'Viver i Serrateix', 'viver-i-serrateix');
